### ISSUE TITLE
please consider publishing the artifacts on maven central

### ISSUE THREAD

**Issue by umesecke** [helpscout/helpscout-api-java#15]
Sadly I couldn't find a maven repository that contains the artifacts. Is there a reason why the artifacts are not published to maven central?

After a quick look over their [requirements](http://central.sonatype.org/pages/requirements.html) I don't think there are any show stoppers. The javadoc variant has to be built and a proper license needs to be added to the pom.xml (which would be nice nonetheless as I couldn't find a specified license either).

Having the artifacts on a public repository makes integrating this client a lot easier.

**Comment by bob983** [comment]
Hi,

that's a good idea. We'll work on it in following weeks.

**Comment by bob983** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;S6tqPbrs&#x2F;122-publish-artifact-in-maven-central"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Publish artifact in maven central</a>

**Comment by bob983** [comment]
Hi, @umesecke, time flies and I can see I haven't attended this issue in a while. While we really wanted to publish the artifact to maven repo, we decided to concentrate on a new API client for the new API we are building.

**Comment by bob983** [comment]
The new API client (for the new API) will be published
