### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by robert-blankenship** [helpscout/helpscout-api-java#2]
Any chance that the sun.misc libs can be replaced with something else? See http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html

**Comment by eytanbiala** [comment]
+1

**Comment by jacobwallace** [comment]
@robert-blankenship @eytanbiala 

This was fixed in the [1.5.0](https://github.com/helpscout/helpscout-api-java/releases/tag/v1.5.0) release. Thanks for pointing this out!
