### ISSUE TITLE
Search endpoint return 400 error code without description

### ISSUE THREAD

**Issue by sphinks** [helpscout/helpscout-api-java#23]
When I try to use search endpoint:

```
Page<SearchConversation> findConversation = client.searchConversations("(subject:\"It is updated!\")", null, null, 1);
```

I get error code 400, but in response, there is no detailed description, which causes NPE in API library. I will add fix for NPE in the library, but nevertheless, some detailed information in case of code 400 should be returned, so it needs to be fixed on backend side. Let me know if you need detailed JSON request to reproduce this issue.

**Comment by sphinks** [comment]
I have made a commit that will fix NPE error (pull request https://github.com/helpscout/helpscout-api-java/pull/20), but I cannot do anything with a problem of backend side - no information returned in a description, in addition to error code 400.

**Comment by bob983** [comment]
I think the error is cause by the query not being encoded properly.

**Comment by sphinks** [comment]
@bob983 what do you mean with 'encoding'? Encoding by the wrapper or some mistake in the query? I see now that I have put '(' at the start of string with closing pair, maybe this cause error. I will check in the evening.

**Comment by bob983** [comment]
I think the query is not url-encoded and the search endpoint does not like it. When you try search query without a space inside, it's OK.

**Comment by sphinks** [comment]
@bob983 you were right. The problem was in URL encoding. Created PR.

**Comment by bob983** [comment]
@sphinks thanks!

**Comment by bob983** [comment]
@sphinks Is this fixed? :)

**Comment by sphinks** [comment]
@bob983 Yes, it was fixed on the side of API wrapper, but the problem that there is no description of error from server side I suppose still exists. Do you know anything about plans for fixing it?

P.S. This issue could be closed, if backend team does not need this as a reminder. :)

**Comment by bob983** [comment]
OK, closing this issue. We're now concentrating on new version of the API.
