### ISSUE TITLE
Create conversation - Attachment Base64 encoding

### ISSUE THREAD

**Issue by KaluKhan** [helpscout/helpscout-api-java#33]
I am creating a new conversation using Mailbox API 2.0 from my Android App in 'Customer Support' section of the application. Api works well, but I am facing 400 Bad Request after attaching an Image in Base64-encoded stream. My code to convert bitmap to Base64 encode is below.

```
fun encodeImageBase64(context: Context?, uri: Uri?): String {
            //converting image to base64 string
            var imageEncoded = ""
            try {
                val bitmap = MediaStore.Images.Media.getBitmap(context?.contentResolver, uri)
                //val bitmap = BitmapFactory.decodeFile(path)
                val stream = ByteArrayOutputStream()
                bitmap.compress(Bitmap.CompressFormat.PNG, 70, stream)
                val imageBytes = stream.toByteArray()
                imageEncoded = Base64.encodeToString(imageBytes, Base64.NO_WRAP)
            } catch (e: Exception) {
                e.printStackTrace()
            }

            return imageEncoded
        }
```
What should be the best way for Base64 encoding of image so that it can seamless upload to HelpScout Server API.
[Question](https://github.com/helpscout/helpscout-api-php/issues/85) Ref. for details.

**Comment by adrianne-helpscout** [comment]
This help request is being handled via our help@helpscout.com support channel. https://secure.helpscout.net/conversation/754835762/0/?folderId=2432440
So, closing this issue.
